export let  todos=[
    {
        id:1,
        name:"elm1",
        isCompleted:false,
    },
    {
        id:2,
        name:"elm2",
        isCompleted:false,
    },
    {
        id:3,
        name:"elm3",
        isCompleted:false,
    },
    {
        id:4,
        name:"elm4",
        isCompleted:false,
    },
    {
        id:5,
        name:"elm5",
        isCompleted:false,
    }
]